language: node_js
node_js:
  - "10.16.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm --prefix "$RESOURCE_DIR" install eslint
  - npm --prefix "$RESOURCE_DIR" install eslint-plugin-promise

script:
  - echo "Deploy!!"

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN