language: node_js
node_js:
  - "10.16.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g eslint
  - npm install -g eslint-plugin-promise
  - npm install

script:
  - npm run build
  - npm run test
  - npm run lint
  - echo "Deploy!!"

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN