language: node_js
node_js:
  - "10.16.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g eslint
  - npm install -g eslint-plugin-promise@latest --save-dev
  - npm install

script:
  - echo "Deploy!!"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN